export const PIE_CHART_REQUEST = 'PIE_CHART_REQUEST'
export const PIE_CHART_SUCCESS = 'PIE_CHART_SUCCESS'
export const PIE_CHART_FAIL = 'PIE_CHART_FAIL'

export const SLICE_CHART_REQUEST = 'SLICE_CHART_REQUEST'
export const SLICE_CHART_SUCCESS = 'SLICE_CHART_SUCCESS'
export const SLICE_CHART_FAIL = 'SLICE_CHART_FAIL'

export const DIFF_CHART_REQUEST = 'DIFF_CHART_REQUEST'
export const DIFF_CHART_SUCCESS = 'DIFF_CHART_SUCCESS'
export const DIFF_CHART_FAIL = 'DIFF_CHART_FAIL'

export const GEO_DATA_REQUEST = 'GEO_DATA_REQUEST'
export const GEO_DATA_SUCCESS = 'GEO_DATA_SUCCESS'
export const GEO_DATA_FAIL = 'GEO_DATA_FAIL'

export const LINE_CHART_REQUEST = 'LINE_CHART_REQUEST'
export const LINE_CHART_SUCCESS = 'LINE_CHART_SUCCESS'
export const LINE_CHART_FAIL = 'LINE_CHART_FAIL'

export const BAR_CHART_REQUEST = 'BAR_CHART_REQUEST'
export const BAR_CHART_SUCCESS = 'BAR_CHART_SUCCESS'
export const BAR_CHART_FAIL = 'BAR_CHART_FAIL'

export const AREA_CHART_REQUEST = 'AREA_CHART_REQUEST'
export const AREA_CHART_SUCCESS = 'AREA_CHART_SUCCESS'
export const AREA_CHART_FAIL = 'AREA_CHART_FAIL'

export const DATA_TABLE_REQUEST = 'DATA_TABLE_REQUEST'
export const DATA_TABLE_SUCCESS = 'DATA_TABLE_SUCCESS'
export const DATA_TABLE_FAIL = 'DATA_TABLE_FAIL'
